name: Push to Main
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - uses: actions/cache@v2
        with:
          path: ./.terraform/providers
          key: ${{ runner.os }}-providers-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-providers-
      - run: terraform init
      - run: terraform fmt -check -recursive -diff
      - run: terraform validate
      - uses: terraform-docs/gh-actions@v0.6.1
        with:
          output-file: README.md
          output-format: markdown
          output-method: inject
          git-push: "true"
      - uses: scaffoldly/bump-version-action@1.0.92-0
        with:
          action: prerelease
          version-file: sly.json
          repo-token: ${{ secrets.GITHUB_TOKEN }}
